#pragma once
void get_m();
void get_s();
void insert_m();
void insert_s();
void del_m();
void del_s();
void update_m();
void update_s();
void calc_m();
void calc_s();
void ut_m();
void ut_s();
void menu();